FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y \
        ca-certificates \
        libhwloc15 \
        python3 && \
    rm -rf /var/lib/apt/lists/*

COPY boost/boost/boostd /usr/local/bin/boostd
COPY boost/boost/boost /usr/local/bin/boost
COPY boost/boost/boostx /usr/local/bin/boostx

RUN chmod +x \
    /usr/local/bin/boostd \
    /usr/local/bin/boost \
    /usr/local/bin/boostx

CMD ["sleep", "infinity"]